### PR TITLE
Update identityPerson.ldif

### LINKED ISSUE #5483: Identity claim with LDAP attribute
Current Identity claims such as http://wso2.org/claims/identity/accountLocked should be able to work with existing LDAP/AD attributes.

### PR DESCRIPTION
**Pull request by SwatiNEC**
Added LDAP attribute for claim mapping of account Lock feature.
Fixes [#5483](https://github.com/wso2/product-is/issues/5483)

### CODE REVIEW

**Comment by SakshiSharma-India** [comment]
Hi @CLAassistant ,
I have a query regarding CLA:
- On clicking the link "Contributor License Agreement" as mentioned by you, the License Agreement page opens with button "Sign in with GitHub to agree". Could you please confirm if CLA is signed just by clicking on this button for an individual or some other information is also required?

Regards,
Sakshi Sharma

**Comment by SakshiSharma-India** [comment]
Hi @CLAassistant ,
Request you to please confirm the query mentioned in previous comment.

Regards,
Sakshi Sharma

**Review by IsuraD — APPROVED** [review]

**Comment by darshanasbg** [comment]
@maheshika: Can you please comment on the query added by @SakshiSharma-India?

**Comment by maheshika** [comment]
Only to click on cla assist and add your name. Nothing else is required.

**Comment by SwatiNEC** [comment]
Hi @godwinamila, @IsuraD

As per the solution provided by me in this PR, the solution is partially merged. But as per the documents of [WSO2 IS](https://docs.wso2.com/display/IS570/Account+Locking+by+Failed+Login+Attempts), we need to use IdentityMgtEventListener with orderId=95. But if we use this then we need to add mapping of failedLockoutCount field in LDAP as this field is missing in identityPerson.ldif. So we also need to add failedLockoutCount field.
Could you please confirm the reason why partial solution was considered for this fix?

**Pull request merged**
