### PR TITLE
Adding new attribute to LDAP to support verification pending email.

### PR DESCRIPTION
**Pull request by dewniMW**
### Proposed changes in this pull request

Adding a new attribute to persist new email address until email verification happens in a scenario where a user's email address is updated.

This PR is related to feature: https://github.com/wso2/product-is/issues/7183

### Follow up actions

After merging the PR, merge https://github.com/wso2/carbon-identity-framework/pull/2654 after updating the new identity-userstore-ldap version.

### CODE REVIEW

**Comment by dewniMW** [comment]
This PR is dependent on https://github.com/wso2-extensions/identity-governance/pull/349. Therefore don’t merge this PR till https://github.com/wso2-extensions/identity-governance/pull/349 is merged.

**Comment by somindatommy** [comment]
@dewniMW Update the PR description with `When to merge` and `Followup actions`.

**Comment by malithie** [comment]
I don't see any use of having an ldap schema for identity claims.
@madurangasiriwardena , @IsuraD , looks like the same pattern has been followed for some time.
Any reason that you can recall of

**Review by emswbandara — APPROVED** [review]

**Comment by emswbandara** [comment]
@malithie we can change the underlying persistence of identity claims to a userstore based storage. Hence we have the ldap schema AFAIK.

**Pull request merged**
